[services.backend]
root = "backend"
buildCommand = "npm install"
startCommand = "node server.js"

[services.backend.ports]
port = 5000
protocol = "TCP"

[services.email-worker]
root = "email-microservice"
buildCommand = "npm install"
startCommand = "node index.js"